### ISSUE TITLE
Write out steps for the initial setup

### ISSUE THREAD

**Issue by lindsayplatt** [rossyndicate/Superior-Plume-Bloom#10]
Copy script/change initials
Add a var init = ‘BGS’ so that we can incorporate into the saved file name in the shared folder

**Comment by steeleb** [comment]
Great question - I wonder if the other option is to just create a shared drive folder for others, and the output goes there automatically? It seems like a lot of extra work for folks to make their own folder and copy/paste and then we incorporate, you know? Let's chat about this tomorrow.

**Comment by lindsayplatt** [comment]
Change instructions to:

1. Setup GEE
2. Make a new folder in GEE called `eePlumB` (include `home` folder instructions here, maybe reference GEE book for setup)
3. Check that they can access the shared `eePlumb_output` folder
4. Share the spreadsheet with mission-date combos and explain how to sign-up.
