### ISSUE TITLE
Start development of image segmentation from labeled tester data

### ISSUE THREAD

**Issue by lindsayplatt** [rossyndicate/Superior-Plume-Bloom#26]
Develop image segmentation process using the newly created labeled rasters (work done after we send to reviewers to meet [this milestone](https://github.com/rossyndicate/Superior-Plume-Bloom/milestone/1)) from citizen scientists.

**Comment by steeleb** [comment]
- [ ] test/train dataset
- [ ] determine best performing classification
- [ ] confusion matrix/accuracy
- [ ] apply to stack
- [ ] export total area (of classes and of available imagery)
