### ISSUE TITLE
Stop user from hitting "next tile" after 5th?

### ISSUE THREAD

**Issue by lindsayplatt** [rossyndicate/Superior-Plume-Bloom#46]
Is it possible to stop a user from hitting "Next Tile" after the 5th? Strange things happen when you do. I ended up over in the Gulf of Guinea.

**Comment by steeleb** [comment]
Hahaha, yeah, that's 0,0 lat lon. :)

I'll try to fix that now.

**Comment by steeleb** [comment]
I changed this to buttons like the validation script. I have files waiting (including updated instructions/images for instructions in my eePlumB_buttons branch.) Making a PR now with these edits.
