### ISSUE TITLE
get rid of .geo column in model output

### ISSUE THREAD

**Issue by steeleb** [rossyndicate/Superior-Plume-Bloom#51]

**Comment by steeleb** [comment]
This will not be fixed in the GEE export step. Will have to be removed when adjusting the summary dataset.

**Comment by lindsayplatt** [comment]
"when adjusting the summary dataset" - is that on my end? Totally OK if so.

**Comment by steeleb** [comment]
Negative! I have an updated tabular file for you shortly!

**Comment by lindsayplatt** [comment]
Amazing!
